-- 1. Create the main table for storing memories
CREATE TABLE public.retain_auth_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    favourite BOOLEAN DEFAULT false,
    metadata JSONB,
    fts TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('english', 
            COALESCE(metadata->>'title', '') || ' ' || 
            COALESCE(metadata->>'summary', '') || ' ' || 
            COALESCE(metadata->>'keywords', '')
        )
    ) STORED
);

-- 2. Create optimized indexes for extremely fast searching
CREATE INDEX idx_retain_auth_memory_fts ON public.retain_auth_memory USING gin(fts);
CREATE INDEX idx_retain_auth_memory_created_at ON public.retain_auth_memory (created_at);
CREATE INDEX idx_retain_auth_memory_favourite ON public.retain_auth_memory (favourite);
CREATE INDEX idx_retain_auth_memory_metadata ON public.retain_auth_memory USING gin(metadata);

-- 3. Ensure Row Level Security (RLS) is disabled for Single-User Mode
ALTER TABLE public.retain_auth_memory DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can only access their own memories" ON public.retain_auth_memory;

-- 4. Create the function required for Gemini's Natural Language SQL Searches
CREATE OR REPLACE FUNCTION public.execute_sql(query_string text)
RETURNS TABLE(id bigint, created_at timestamptz, metadata jsonb)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY EXECUTE query_string;
END;
$$;

-- 5. Add helpful documentation comments to the schema
COMMENT ON TABLE public.retain_auth_memory IS 'Stores user memories with AI-extracted metadata and full-text search (Single User Mode)';
COMMENT ON FUNCTION public.execute_sql IS 'Executes dynamic SQL queries for AI-driven NLP search functionality';
